POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzdWFyaW8iLCJpZCI6IjY2M2U3MzQyOWZkZTViZDkxMWY0NDRhNSIsImlhdCI6MTcxNTM2ODc4MSwiZXhwIjoxNzE1MzcyMzgxfQ.dLQ8t98TWhtLDgMeLhO17oDz_lxBrfXc-j7FKEvtZiI

{
  "title": "Titulo de prueba con TOKEN",
  "author": "Autor de prueba con TOKEN",
  "url": "URL de prueba con TOKEN",
  "likes": 9
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzdWFyaW8gMiIsImlkIjoiNjYzZTczYzA5ZmRlNWJkOTExZjQ0NGMyIiwiaWF0IjoxNzE1MzY5MzAyLCJleHAiOjE3MTUzNzI5MDJ9.tpkeNRKcsicn6mIlQzbDAr4GHOMSKF0CuTYabx6avJI

{
  "title": "Titulo de prueba 2 con TOKEN",
  "author": "Autor de prueba 2 con TOKEN",
  "url": "URL de prueba 2 con TOKEN",
  "likes": 5
}