POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzdWFyaW8gMiIsImlkIjoiNjYzZTQ0ZjM3NTg4ZmY2ZDJiNDJiNjY5IiwiaWF0IjoxNzE1MzU2OTM1fQ.km5hP2S137KNnjNo4wYp-Y6NsgAfSxWDpSA0R3_X5q8

{
  "title": "Titulo de prueba con TOKEN",
  "author": "Autor de prueba con TOKEN",
  "url": "URL de prueba con TOKEN",
  "likes": 9
}