POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "Usuario",
  "name": "Nuevo Usuario",
  "password": "123456789"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "Usuario 2",
  "name": "Nuevo Usuario 2",
  "password": "987654321"
}